### ISSUE TITLE
USA005-01 à la connexion, je peux afficher la page d'authentification

### ISSUE THREAD

**Issue by roddet** [DTAFormation/ecommerce-frontend-desktop#1]
Lorsque je me dirige vers le site, cela me dirige vers une page d'authentification.
la page "Authentification" contient : 
-> Un champ login
-> Un champ mot de passe.
->un bouton login

ces champs doivent apparaitre si l'administateur appuie sur le bouton "logout" de la barre de navigation.
si l'authentification échoue, la navigation ne doit pas avoir lieu.
si l'authentification réussit, l'administateur doit pouvoir accèder à ses menus.

**Comment by nstoffels** [comment]
CA terminé, début du développement.

**Comment by nstoffels** [comment]
developpement en local terminé, préparation du développement avec un mock.

**Comment by nstoffels** [comment]
manque test unitaire

**Comment by ducloux-b** [comment]
-Mettre un message quand on met un couple login/mdp incorrect
-Nettoyage des console.log()3
-Réaliser tests unitaires + Revue

**Comment by dlecan** [comment]
Terminé
