### ISSUE TITLE
USA002-02 - En tant qu'administrateur, je peux accéder à la liste des clients

### ISSUE THREAD

**Issue by ducloux-b** [DTAFormation/ecommerce-frontend-desktop#10]
Lorsque l'administrateur est sur la page d'accueil, il a accès au menu "Liste des clients".

Lorsque l'administrateur clique sur le menu "Liste des clients", la page "Liste des clients" s'affiche.Cette liste  contient :

L'identifiant du client
Le nom du client
Le prénom du client
L'email du client
L'adresse du client

**Comment by chanceED** [comment]
CA et dev terminés

**Comment by nstoffels** [comment]
revue en cours

**Comment by nstoffels** [comment]
revue terminée

**Comment by ducloux-b** [comment]
-Permettre la gestion de plusieurs adresses
-Se connecter à la base pour récupérer les données

**Comment by PaulieKlein** [comment]
- enlever le mot de passe

**Comment by PaulieKlein** [comment]
- lors du get ne pas ramener le mot de passe

**Comment by soffredo** [comment]
Critères d'acceptation : 
- Enlever le mot de passe du tableau
- Ne pas GET le mot de passe

**Comment by dlecan** [comment]
Terminé
