### ISSUE TITLE
USA002-01 - En tant qu'administrateur, je peux créer un client

### ISSUE THREAD

**Issue by ducloux-b** [DTAFormation/ecommerce-frontend-desktop#11]
Lorsque l'administrateur est sur la page d'acceuil créer client, il a accès à un formulaire ayant:
- Nom
- Prénom
- Adresse (composée d'un numéro de rue, une rue et une ville)
- Login
- Password

Lorsqu'il clique sur créer, et qu'un nouveau client est créé. Il est ensuite renvoyé sur la même page avec écrit "Client créé" sinon, il est tout de même renvoyé sur la même page mais le massage affiché est "Le client n'a pas été créé".

**Comment by ducloux-b** [comment]
J'ai réalisé la revue.

**Comment by ducloux-b** [comment]
-Permettre de gérer plusieurs adresses (ajout, affichage,...)
-Se connecter à la BDD pour obtenir les données
-Ajouter de la validation sur les champs en fonction du modèle
-Indiquer que le login est un mail

**Comment by PaulieKlein** [comment]
- validation des champs
- supprimer adresse

**Comment by dlecan** [comment]
Terminé
