### ISSUE TITLE
USA002-03 - En tant qu'administrateur, je peux modifier les informations d'un client

### ISSUE THREAD

**Issue by ducloux-b** [DTAFormation/ecommerce-frontend-desktop#12]
Lorsque l'administrateur est sur la page d'accueil, il a accès au menu "Liste des clients".

Lorsque l'administrateur clique sur le menu "Liste des clients", la page "Liste des clients" s'affiche.Cette liste contient :
- L'identifiant du client
- Le nom du client
- Le prénom du client
- L'email du client
- L'adresse du client
- Un bouton "modifier client" permettant de modifier les informations d'un client.

En cliquant dessus ,les informations du client s'affichent,l'administrateur a ensuite la possibilité de modifier ces informations et de les enregistrer.Les modifications sont ensuite répercutées dans la liste des clients

**Comment by Joux17** [comment]
Il faut ajouter les champs pour l'adresse dans le formulaire de update. 
Le numéro, la rue, la ville.
Chancia s'en charge.

**Comment by nstoffels** [comment]
intégration backend à faire + validation

**Comment by ducloux-b** [comment]
-Permettre la gestion de plusieurs adresses
-Se connecter à la base pour récupérer les données

**Comment by PaulieKlein** [comment]
- gestion des adresses 
- modification affichage

**Comment by PaulieKlein** [comment]
- enlever le mot de passe
- modifier email
- lors du get ne pas ramener le mot de passe

**Comment by RomainFarau** [comment]
- Ajouter bouton sous les adresses pour ajouter nouvelle adresse

**Comment by soffredo** [comment]
# Revue :

Petit bug, certaines conditions dans lesquelles on doit cliquer 2 fois sur le bouton d'envoi.

Au niveau des adresses :
- On peut vider une adresse et l'enregistrer vide, normal ?
- Peut-on supprimer une adresse ? La passer à inactive ?

Ajouter un test unitaire ajoutant une adresse à un client existant.

**Comment by dlecan** [comment]
Terminé
