### ISSUE TITLE
USA002-04 - En tant qu'administrateur, je peux supprimer un client

### ISSUE THREAD

**Issue by ducloux-b** [DTAFormation/ecommerce-frontend-desktop#13]
La possibilité de supprimer un client se fait grâce à une bouton `x` inclus en face du client désiré.
Lorsqu'on clique sur ce bouton une requête http de type **DELETE** doit être envoyée en base de données afin de supprimer le client.

Dans l'idéal, l'affichage devrait alors se rafraîchir et on ne devrait plus voir le client supprimé sur la page des clients.

**Comment by nstoffels** [comment]
intégration backend à faire + validation.

**Comment by ducloux-b** [comment]
-Permettre la gestion de plusieurs adresses
-Se connecter à la base pour récupérer les données

**Comment by PaulieKlein** [comment]
- enlever message d'erreur

**Comment by PaulieKlein** [comment]
- test protractor

**Comment by soffredo** [comment]
Bug suppression de client,
- Service appelé parfois, parfois non
- Quand service appelé, client supprimé parfois, parfois non.

**Comment by dlecan** [comment]
Inactivation d'un compte au lieu d'une suppression

Terminé
