### ISSUE TITLE
USA003-02 - En tant qu'administrateur, je peux annuler une commande

### ISSUE THREAD

**Issue by ducloux-b** [DTAFormation/ecommerce-frontend-desktop#15]

**Comment by PaulieKlein** [comment]
- afficher toutes les commandes avec statut
- changement de statut de "en cours" à "annulé" pour la commande
- bouton accessible depuis la liste des commandes ou depuis les détails d'un client

**Comment by soffredo** [comment]
Critère d'acceptation :
- Afficher un bouton annuler à coté des commandes "en cours"
- Un clic sur ce bouton passe le statut de la commande de "en cours" à "annulée"

**Comment by dlecan** [comment]
Terminé
