### ISSUE TITLE
USA003-03 - En tant qu'administrateur, je peux rechercher une commande unique

### ISSUE THREAD

**Issue by ducloux-b** [DTAFormation/ecommerce-frontend-desktop#16]

**Comment by PaulieKlein** [comment]
- ajouter champ de recherche (id commande)
- afficher détails commande

**Comment by soffredo** [comment]
Critères d'acceptation :
- Champ de texte dans lequel on insère l'ID de la commande
- A la validation, envoie directement à la page de détails de la commande.

**Comment by dlecan** [comment]
Terminé
