### ISSUE TITLE
USA004-01 - En tant qu'administrateur, je peux visualiser les meilleurs clients

### ISSUE THREAD

**Issue by ducloux-b** [DTAFormation/ecommerce-frontend-desktop#17]

**Comment by PaulieKlein** [comment]
meilleurs clients:
- max 10
- trier par prix total des commandes
- trier par nombre de commandes

**Comment by PaulieKlein** [comment]
- tester avec protractor

**Comment by LebonJo** [comment]
Afficher pour chaque produit :
- le rang
- le nom
- le prenom
- le nombre de commande
- ou le total des dépenses sur le site

Tout le tri est à faire dans le frontend, on récupère tous les clients avec le service existant.

**Comment by dlecan** [comment]
Terminé
