### ISSUE TITLE
USA004-03 - En tant qu'administrateur, je peux visualiser les clients ayant acheté un produit donné

### ISSUE THREAD

**Issue by ducloux-b** [DTAFormation/ecommerce-frontend-desktop#19]

**Comment by PaulieKlein** [comment]
- ajouter, dans la page de la liste des produits, un bouton permettant devoir les clients (top 10) ayant achetés chaque produit. 
- pour chaque client : rang, nom, prénom et lien vers détails client

**Comment by LebonJo** [comment]
- créer une nouvelle page html
- créer un nouveau controlleur dans le module de stats
- faire le routing
- ajouter le bouton dans le tableau de la liste des produits
- faire les tests unitaires du controlleur (et service si besoin)

**Comment by soffredo** [comment]
Revue : ok

**Comment by dlecan** [comment]
Terminé
