### ISSUE TITLE
USA001-04 - En tant qu'administrateur, je peux accéder à la liste des produits

### ISSUE THREAD

**Issue by roddet** [DTAFormation/ecommerce-frontend-desktop#2]
Lorsque l'administrateur est sur la page d'accueil, il a accès au menu "Liste de produits".

Lorsque l'administrateur clique sur le menu "Liste de produits", la page "Liste de produits" s'affiche. La page "Liste de produits" contient : 
- Une image du produit
- Le libellé du produit
- Un lien vers le détail de chaque produit

**Comment by nstoffels** [comment]
Terminé.

**Comment by nstoffels** [comment]
Erreur à la fermeture,
seul le critère d'acceptation était finit

**Comment by nstoffels** [comment]
developpement terminé, test unitaire en cours

**Comment by nstoffels** [comment]
test unitaire terminé, en attente d'une revue de code

**Comment by Joux17** [comment]
J'ai modifié la balise image des produits, il y avait une erreur dans la console.

<img data-ng-src="{{produit.image}}" alt="le produit {{produit.id}}" height="200" width="200"/></td>

au lieu de :

<img src="{{produit.image}}" alt="le produit {{produit.id}}" height="200" width="200"/></td>

**Comment by ducloux-b** [comment]
-Corriger caractéristiques affichées
-Enlever modale
