### ISSUE TITLE
USA001-05 - En tant qu'administrateur, je souhaite pouvoir rechercher un produit par mot clé

### ISSUE THREAD

**Issue by Joux17** [DTAFormation/ecommerce-frontend-desktop#22]
Lorsque l'administrateur est sur la page d'affichage des produits, il a accès à un champ de recherche lui permettant d'afficher les produits par mot clé.

Lorsqu'il commence à rentrer le mot clé la liste est mise à jour en temps réel.

**Comment by nstoffels** [comment]
revue faite sur le filtre.
