### ISSUE TITLE
USA007 - Transformer les DELETE en Actif / Passif 

### ISSUE THREAD

**Issue by NathanGUILLOTEAU** [DTAFormation/ecommerce-frontend-desktop#29]
Pour les produits et les clients, il ne faut pas vraiment les supprimer. Il faut mettre en place un principe d'actif/passif comme cela a été fait sur client. 

Pour une question d’ergonomie, si on pouvait avoir des couleurs de fonds de lignes différentes selon l'état dans le tableau d'affichage, ça serait top.

**Comment by dlecan** [comment]
Terminé
