### ISSUE TITLE
USA001-01 - En tant qu'administrateur, je peux créer un produit

### ISSUE THREAD

**Issue by roddet** [DTAFormation/ecommerce-frontend-desktop#3]
Lorsque l'administrateur est sur la page produit, il a accès à un formulaire permettant de créer un produit et ayant comme champ :
- Libelle (String)
- Caractéristique (String)
- Catégorie (String)
- Image (String)
- Prix (float)

Lorsqu'il clique sur créer, un nouveau produit est créé et est ajouté en base.

**Comment by nstoffels** [comment]
fin, mais us nécessaire pour améliorer le contrôle des champs.

**Comment by ducloux-b** [comment]
-Ajouter de la validation sur les champs (en fonction du modèle)
-(?) Upload de fichier pour l'image
