### ISSUE TITLE
USA001-02 - En tant qu'administrateur, je peux modifier les informations d'un produit

### ISSUE THREAD

**Issue by roddet** [DTAFormation/ecommerce-frontend-desktop#4]

**Comment by Remidendooven** [comment]
Lorsque l'administrateur est sur la page d'accueil, il a accès au menu "Liste des produits".

Lorsque l'administrateur clique sur le menu "Liste des clients", la page "Liste des clients" s'affiche.

Création d'un bouton "modifier produit" permettant de modifier les informations d'un produit .
En cliquant dessus ,les informations du produit s'affichent,l'administrateur a ensuite la possibilité de modifier ces informations et de les enregistrer.Les modifications sont ensuite répercutées dans la liste des produits.

**Comment by ducloux-b** [comment]
Revue de code effectuée, à priori rien à signaler

**Comment by nstoffels** [comment]
fin.

**Comment by ducloux-b** [comment]
-Corriger critères d'acceptation (faute de relecture)
