### ISSUE TITLE
USA001-03 - En tant qu'administrateur, je peux supprimer un produit

### ISSUE THREAD

**Issue by roddet** [DTAFormation/ecommerce-frontend-desktop#5]
Lorsque l'administrateur est sur la page d'accueil, il a accès au menu "Liste de produits".

Lorsque l'administrateur clique sur le menu "Liste de produits", la page "Liste de produits" s'affiche. La page "Liste de produits" contient :

Une image du produit
Le libellé du produit
Un lien vers le détail de chaque produit;
Un bouton supprimer pour supprimer le produit qui'l désire.
En cliquant sur ce dernier,le produit est supprimé de la liste et la liste des produits s'affiche sans le produit supprimé

**Comment by nstoffels** [comment]
début du développement de l'option supprimer produit.

**Comment by nstoffels** [comment]
fin développement développer produit, début de la programmation du test unitaire.

**Comment by nstoffels** [comment]
fin de la programmation du test unitaire, en attente de la revue

**Comment by ducloux-b** [comment]
-Remplacer windows.update par un GET en angular qui met à jour les données affichées
