### ISSUE TITLE
USA005-03 - En tant qu'administrateur, je souhaite pouvoir accéder à la page d'administration

### ISSUE THREAD

**Issue by ducloux-b** [DTAFormation/ecommerce-frontend-desktop#8]
Lorsque l'administrateur vient de se logger, il a accès à la page d'administration.
La page d'administration présente les sections accessibles et les fonctionnalités d'administration qui y sont disponibles.

Lorsque l'administrateur clique sur le menu/lien "Administrer produits", la page de gestion des produits s'affiche.
Lorsque l'administrateur clique sur le menu/lien "Administrer clients", la page de gestion des clients s'affiche.
Lorsque l'administrateur clique sur le menu/lien "Administrer commandes", la page de gestion des commandes s'affiche.
Lorsque l'administrateur clique sur le menu/lien "Statistiques e-Commerce", la page de statistiques.

**Comment by ducloux-b** [comment]
La page devrait fonctionner "mécaniquement", il va falloir s'assurer que les bons liens soient réalisés.

**Comment by ducloux-b** [comment]
Les tests unitaires ont été réalisés.

**Comment by Joux17** [comment]
Je fais la revue !

**Comment by nstoffels** [comment]
fin.
